steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t southamerica-east1-docker.pkg.dev/microservices-422001/image-registry/auth-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'southamerica-east1-docker.pkg.dev/microservices-422001/image-registry/auth-ms',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/367390259998/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'